export const landingCopy = {
  en: {
    skip: "Skip to main content",
    navLoop: "The loop",
    navControlRoom: "Control Room",
    navMemory: "Memory",
    navAgents: "Agents",
    navDocs: "Docs",
    navInstall: "Install",
    githubStar: "GitHub",
    languageLabel: "Switch language",
    themeLight: "Light mode",
    themeDark: "Dark mode",
    brandTagline: "Causal memory for agents",

    heroBadge: "v1.0 · stable",
    heroBadgeNote: "Local-first causal memory for coding agents",
    heroTitleA: "Your agents forget why.",
    heroTitleB: "Rationale remembers.",
    heroBody:
      "Before an agent changes your code, Rationale hands it the rules, decisions and relationships that govern it. After the change, the knowledge that stays true is written back to your repository — automatically, with the rules you pin kept out of any agent's reach.",
    installCta: "Install v1.0",
    quickstartCta: "Quick start",
    stateLine: "Git + Codebase Memory · No account · No telemetry · 127.0.0.1",
    heroVisualLabel: "Illustrative context operation",
    hudTitle: "prepare_change",
    hudTarget: "src/payments/retry.rs::charge",
    hudConstraint: "pinned rule",
    hudDecision: "decision",
    hudRelationship: "explained edge",
    hudBudget: "packet",
    hudCaptured: "record.committed",
    hudIllustrative: "illustrative",

    metrics: [
      { value: "5", label: "MCP tools" },
      { value: "6", label: "agent actions" },
      { value: "3", label: "agents supported" },
      { value: "5", label: "platforms, one binary" },
      { value: "0", label: "accounts or telemetry" },
    ],

    problemEyebrow: "The failure mode",
    problemTitle: "You explained the rule. The next chat never heard it.",
    problemQuote: "“Never retry a payment that already reached the bank.”",
    problemBody:
      "It works in Monday’s conversation. On Thursday a fresh agent sees only the code, removes the guard, and calls it a cleanup.",
    problemAnswer:
      "Rationale keeps the rule next to the code it governs — and hands it to every agent before it touches that code.",

    loopEyebrow: "The loop",
    loopTitle: "Context before the change. Memory after it.",
    loopBody: "No approval queue. Agents capture what they learn; you keep authority over what must not move.",
    loopSteps: [
      { tool: "Codebase Memory", title: "Locate", body: "Find the symbol, its callers and the files around it." },
      {
        tool: "prepare_change",
        title: "Prepare",
        body: "Governing rules, explained relationships, the structural neighborhood and the target’s code — within a token ceiling.",
      },
      { tool: "your tests", title: "Change", body: "The smallest change consistent with that context." },
      {
        tool: "finalize_change",
        title: "Capture",
        body: "Durable knowledge becomes canonical Records in the same call. Noise and duplicates are discarded with a reason.",
      },
      {
        tool: "rationale pin",
        title: "Pin",
        body: "Fix the rules no agent may replace. Any attempt becomes a conflict only you resolve.",
      },
    ],

    packetEyebrow: "The packet",
    packetTitle: "Everything the agent must know. Nothing it doesn’t.",
    packetBody:
      "A bounded packet compiled for one target and one intent. Governing knowledge is never truncated, and the budget is a ceiling — not a target.",
    packetPoints: [
      "Constraints and decisions, each with authority and provenance",
      "Why relationships exist, with their live structural state",
      "A bounded subgraph: callers, callees, dependencies, tests",
      "Intent conflicts, risks and honest unknowns",
    ],
    packetFile: "packet.json",

    roomEyebrow: "Control Room",
    roomTitle: "See what every agent was given — live.",
    roomBody:
      "`rationale ui` opens a local, read-only mission control: the working subgraph in 3D, the memory that explains it, and every session’s activity as it streams.",
    roomFeatures: [
      { title: "Working subgraph", body: "Nodes colored by their role in the change, edges by structural state." },
      { title: "Causal overlay", body: "Rings mark what the canon explains. Select any node to read why." },
      { title: "Live activity", body: "Claude Code, Codex, Cursor and the CLI, streamed over SSE." },
      { title: "Memory browser", body: "Provenance, authority, bindings and pending conflicts." },
    ],
    roomSafety: "127.0.0.1 only · GET-only · embedded in the binary",
    roomTabs: ["Graph", "Activity", "Memory", "System"],
    roomLive: "live",
    roomOperation: "operation · Claude Code",
    roomIntent: "cap payment retries at three",
    roomNodes: "nodes",
    roomRelations: "relations",
    roomRecords: "records",
    roomPacket: "packet",
    roomOf: "of",

    memoryEyebrow: "Memory & authority",
    memoryTitle: "Agents write memory. You keep authority.",
    memoryBody: "Every Record carries where it came from and how much it can be moved. The boundary is enforced, not suggested.",
    memoryCards: [
      {
        tag: "provenance",
        title: "Always attributed",
        body: "An agent’s assertion records its client, session and operation. It is never presented as something a person stated.",
      },
      {
        tag: "pinned",
        title: "Rules that hold",
        body: "Pin a rule and every agent can use it — none can replace it.",
      },
      {
        tag: "conflict",
        title: "You decide",
        body: "An agent that tries to supersede a pinned rule writes nothing. You keep the rule or adopt the new one.",
      },
    ],
    memoryTerminalNote: "Human-only commands: they require an interactive terminal and declared authority.",
    commentPin: "# agents can use it, never replace it",
    commentConflicts: "# assertions that collided with a pinned rule",
    commentResolve: "# your call, recorded for audit",

    edgesEyebrow: "Relationship why",
    edgesTitle: "Not just what calls what. Why it must.",
    edgesBody:
      "A Record can explain a relationship. On every call Rationale re-derives its state from the provider — and never deletes the explanation.",
    edgeStates: [
      { state: "observed", body: "The direct relationship exists in the current index." },
      { state: "indirect", body: "No longer direct, but a bounded path still connects both ends." },
      { state: "orphaned", body: "It can’t be located. The explanation may be stale — flagged, never deleted." },
      { state: "unknown", body: "The provider couldn’t verify it. Absence is not proof." },
    ],

    systemsEyebrow: "Three systems / one boundary",
    systemsTitle: "Structure tells you where. Git tells you what. Rationale protects why.",
    gitQuestion: "What changed, when, and in which revision?",
    memoryQuestion: "Where is it, and how is it connected?",
    rationaleQuestion: "Why does it exist, what must survive, and who can move it?",

    agentsEyebrow: "Quick start / by agent",
    agentsTitle: "Works with the agents you already use.",
    agentsBody:
      "The installer registers one MCP server per agent with its absolute path; `install-agent` writes the protocol into your project. Remove it all with `uninstall-agent`.",
    agentsDocs: "Open agents and MCP docs →",
    claudeTitle: "Installed slash commands",
    claudeNote: "`/rationale-conflicts` is human-only: the agent cannot decide for you.",
    codexTitle: "Ask in plain language",
    codexPrepare: "Prepare this change with Rationale for `<target>` with intent `<intent>`.",
    codexExplain: "Explain `<target>` before changing it.",
    codexCapture: "Capture this change with Rationale.",
    codexHealth: "Check Rationale health.",
    codexNote: "Codex reads the protocol from `AGENTS.md` and calls the MCP tools. No fictional slash commands.",
    cursorTitle: "An always-on rule",
    cursorBody: "Cursor gets `.cursor/rules/rationale.mdc` in the project and a user-scoped MCP server that works from the Dock.",

    trustEyebrow: "Trust by design",
    trustTitle: "Local by default. Honest about uncertainty.",
    trustItems: [
      { title: "Canon in Git", body: "`.rationale/` is plain YAML, reviewed in the same pull request as the code." },
      { title: "Traces stay home", body: "Activity keeps identifiers and a one-line intent. Never code, prompts or Record content." },
      { title: "Read-only mission control", body: "127.0.0.1, GET-only, Host-validated, embedded assets." },
      { title: "Provider boundary", body: "Codebase Memory only through its public tools. Unavailable means unknown, never complete." },
    ],

    releaseEyebrow: "Release truth",
    releaseTitle: "1.0 is stable. Here is what that means.",
    releaseBody: "The full loop is implemented, tested and used on Rationale’s own repository.",
    releaseVerified: [
      "366 Rust tests, Clippy, RustSec and schema validation",
      "Clean-checkout and packaged-binary verification",
      "Registration migration for Claude Code, Codex and Cursor",
      "Dogfood: a real change captured and retrieved end to end",
    ],
    releaseOpen: [
      "Lexical intent-conflict polarity is a noisy hint",
      "Some ADRs are implemented but still proposed",
    ],
    releaseVerifiedLabel: "verified",
    releaseOpenLabel: "open, stated plainly",
    releaseEvidence: "Read the evidence →",
    releaseLimits: "Known limits →",

    installEyebrow: "Install / about a minute",
    installTitle: "Give your agents a memory for why.",
    installBody: "The installer verifies checksums and uses the stable channel. Updating or uninstalling never touches `.rationale/`.",
    installCompanion: "01 / Codebase Memory · recommended",
    installStep1: "02 / Install Rationale · macOS + Linux",
    installStep2: "03 / Inside your repository",
    installStep3: "04 / Open the Control Room",
    installWindows: "Windows? The PowerShell installer is in the quickstart.",
    installRestart: "Restart your agent. In Claude Code run `/rationale-health`; in Codex ask “Check Rationale health.”",
    installCopy: "Copy command",
    copied: "Copied",
    copyFailed: "Select and copy",

    docsEyebrow: "Documentation",
    docsTitle: "Everything you need to verify the claim.",
    docsCards: [
      { slug: "quickstart", label: "Start", title: "Five-minute quickstart", body: "Install, connect an agent, first governed change." },
      { slug: "workflow", label: "Operate", title: "The loop", body: "Prepare, change, capture — and where a person decides." },
      { slug: "control-room", label: "Observe", title: "Control Room", body: "The graph, the memory and live activity." },
      { slug: "concepts", label: "Understand", title: "Core concepts", body: "Records, provenance, authority, relationships." },
      { slug: "mcp-reference", label: "Integrate", title: "MCP reference", body: "Five tools, six prompts, one boundary." },
      { slug: "evidence", label: "Verify", title: "Evidence", body: "What 1.0 was verified against, and what’s open." },
    ],

    footerLine: "Your repo. Your process. Your context.",
    footerDocs: "Docs",
    footerGithub: "GitHub",
    footerLicense: "MIT License",
    footerStatus: "v1.0.0 · no remote telemetry",
  },
  es: {
    skip: "Saltar al contenido principal",
    navLoop: "El ciclo",
    navControlRoom: "Control Room",
    navMemory: "Memoria",
    navAgents: "Agentes",
    navDocs: "Docs",
    navInstall: "Instalar",
    githubStar: "GitHub",
    languageLabel: "Cambiar idioma",
    themeLight: "Modo claro",
    themeDark: "Modo oscuro",
    brandTagline: "Memoria causal para agentes",

    heroBadge: "v1.0 · estable",
    heroBadgeNote: "Memoria causal local-first para agentes de código",
    heroTitleA: "Tus agentes olvidan el porqué.",
    heroTitleB: "Rationale lo recuerda.",
    heroBody:
      "Antes de que un agente cambie tu código, Rationale le entrega las reglas, decisiones y relaciones que lo gobiernan. Después del cambio, el conocimiento que sigue siendo cierto vuelve a tu repositorio — de forma automática, y con las reglas que fijas fuera del alcance de cualquier agente.",
    installCta: "Instalar v1.0",
    quickstartCta: "Empieza rápido",
    stateLine: "Git + Codebase Memory · Sin cuenta · Sin telemetría · 127.0.0.1",
    heroVisualLabel: "Operación de contexto ilustrativa",
    hudTitle: "prepare_change",
    hudTarget: "src/payments/retry.rs::charge",
    hudConstraint: "regla fijada",
    hudDecision: "decisión",
    hudRelationship: "arista explicada",
    hudBudget: "packet",
    hudCaptured: "record.committed",
    hudIllustrative: "ilustrativo",

    metrics: [
      { value: "5", label: "herramientas MCP" },
      { value: "6", label: "acciones de agente" },
      { value: "3", label: "agentes soportados" },
      { value: "5", label: "plataformas, un binario" },
      { value: "0", label: "cuentas o telemetría" },
    ],

    problemEyebrow: "El modo de fallo",
    problemTitle: "Explicaste la regla. El siguiente chat nunca la escuchó.",
    problemQuote: "“Nunca reintentes un pago que ya llegó al banco.”",
    problemBody:
      "Funciona en la conversación del lunes. El jueves, un agente nuevo solo ve el código, quita la guarda y lo llama limpieza.",
    problemAnswer:
      "Rationale mantiene la regla junto al código que gobierna — y se la entrega a cada agente antes de que toque ese código.",

    loopEyebrow: "El ciclo",
    loopTitle: "Contexto antes del cambio. Memoria después.",
    loopBody: "Sin cola de aprobación. Los agentes capturan lo que aprenden; tú conservas la autoridad sobre lo que no debe moverse.",
    loopSteps: [
      { tool: "Codebase Memory", title: "Localizar", body: "Encuentra el símbolo, sus callers y los archivos alrededor." },
      {
        tool: "prepare_change",
        title: "Preparar",
        body: "Reglas gobernantes, relaciones explicadas, la vecindad estructural y el código del target — dentro de un techo de tokens.",
      },
      { tool: "tus tests", title: "Cambiar", body: "El cambio mínimo coherente con ese contexto." },
      {
        tool: "finalize_change",
        title: "Capturar",
        body: "El conocimiento durable se vuelve Records canónicos en la misma llamada. El ruido y los duplicados se descartan con motivo.",
      },
      {
        tool: "rationale pin",
        title: "Fijar",
        body: "Fija las reglas que ningún agente puede reemplazar. Cualquier intento se vuelve un conflicto que solo tú resuelves.",
      },
    ],

    packetEyebrow: "El packet",
    packetTitle: "Todo lo que el agente debe saber. Nada que no.",
    packetBody:
      "Un packet acotado, compilado para un target y una intención. El conocimiento gobernante nunca se recorta, y el presupuesto es un techo — no una meta.",
    packetPoints: [
      "Constraints y decisiones, cada una con autoridad y procedencia",
      "Por qué existen las relaciones, con su estado estructural vivo",
      "Un subgrafo acotado: callers, callees, dependencias, tests",
      "Conflictos con la intención, riesgos y desconocidos honestos",
    ],
    packetFile: "packet.json",

    roomEyebrow: "Control Room",
    roomTitle: "Mira qué recibió cada agente — en vivo.",
    roomBody:
      "`rationale ui` abre un centro de control local y de solo lectura: el subgrafo de trabajo en 3D, la memoria que lo explica y la actividad de cada sesión mientras llega.",
    roomFeatures: [
      { title: "Subgrafo de trabajo", body: "Nodos coloreados por su rol en el cambio, aristas por estado estructural." },
      { title: "Overlay causal", body: "Los anillos marcan lo que explica el canon. Selecciona un nodo para leer el porqué." },
      { title: "Actividad en vivo", body: "Claude Code, Codex, Cursor y la CLI, por SSE." },
      { title: "Navegador de memoria", body: "Procedencia, autoridad, bindings y conflictos pendientes." },
    ],
    roomSafety: "Solo 127.0.0.1 · solo GET · embebido en el binario",
    roomTabs: ["Grafo", "Actividad", "Memoria", "Sistema"],
    roomLive: "en vivo",
    roomOperation: "operación · Claude Code",
    roomIntent: "limitar los reintentos de pago a tres",
    roomNodes: "nodos",
    roomRelations: "relaciones",
    roomRecords: "records",
    roomPacket: "packet",
    roomOf: "de",

    memoryEyebrow: "Memoria y autoridad",
    memoryTitle: "Los agentes escriben memoria. Tú conservas la autoridad.",
    memoryBody: "Cada Record lleva de dónde viene y cuánto se puede mover. La frontera se aplica, no se sugiere.",
    memoryCards: [
      {
        tag: "procedencia",
        title: "Siempre atribuido",
        body: "La afirmación de un agente registra su cliente, sesión y operación. Nunca se presenta como algo que declaró una persona.",
      },
      {
        tag: "pinned",
        title: "Reglas que se sostienen",
        body: "Fija una regla y todos los agentes pueden usarla — ninguno puede reemplazarla.",
      },
      {
        tag: "conflicto",
        title: "Tú decides",
        body: "Un agente que intenta reemplazar una regla fijada no escribe nada. Conservas la regla o adoptas la nueva.",
      },
    ],
    memoryTerminalNote: "Comandos solo humanos: exigen una terminal interactiva y autoridad declarada.",
    commentPin: "# los agentes la usan, nunca la reemplazan",
    commentConflicts: "# afirmaciones que chocaron con una regla fijada",
    commentResolve: "# tu decisión, registrada para auditoría",

    edgesEyebrow: "El porqué de las relaciones",
    edgesTitle: "No solo qué llama a qué. Por qué debe hacerlo.",
    edgesBody:
      "Un Record puede explicar una relación. En cada llamada Rationale vuelve a derivar su estado desde el proveedor — y nunca borra la explicación.",
    edgeStates: [
      { state: "observed", body: "La relación directa existe en el índice actual." },
      { state: "indirect", body: "Ya no es directa, pero un camino acotado sigue conectando los extremos." },
      { state: "orphaned", body: "No se puede localizar. La explicación puede estar obsoleta — se señala, nunca se borra." },
      { state: "unknown", body: "El proveedor no pudo verificarla. La ausencia no es prueba." },
    ],

    systemsEyebrow: "Tres sistemas / una frontera",
    systemsTitle: "La estructura dice dónde. Git dice qué. Rationale protege por qué.",
    gitQuestion: "¿Qué cambió, cuándo y en qué revisión?",
    memoryQuestion: "¿Dónde está y cómo se conecta?",
    rationaleQuestion: "¿Por qué existe, qué debe sobrevivir y quién puede moverlo?",

    agentsEyebrow: "Inicio rápido / por agente",
    agentsTitle: "Funciona con los agentes que ya usas.",
    agentsBody:
      "El instalador registra un servidor MCP por agente con su ruta absoluta; `install-agent` escribe el protocolo en tu proyecto. Retíralo todo con `uninstall-agent`.",
    agentsDocs: "Ver agentes y MCP en los docs →",
    claudeTitle: "Slash commands instalados",
    claudeNote: "`/rationale-conflicts` es solo humano: el agente no puede decidir por ti.",
    codexTitle: "Pídelo por escrito",
    codexPrepare: "Prepara este cambio con Rationale para `<target>` con intención `<intent>`.",
    codexExplain: "Explícame `<target>` antes de modificarlo.",
    codexCapture: "Captura este cambio con Rationale.",
    codexHealth: "Comprueba la salud de Rationale.",
    codexNote: "Codex lee el protocolo en `AGENTS.md` y llama las herramientas MCP. Sin slash commands ficticios.",
    cursorTitle: "Una regla siempre activa",
    cursorBody: "Cursor recibe `.cursor/rules/rationale.mdc` en el proyecto y un servidor MCP por usuario que funciona desde el Dock.",

    trustEyebrow: "Confianza por diseño",
    trustTitle: "Local por defecto. Honesto sobre la incertidumbre.",
    trustItems: [
      { title: "Canon en Git", body: "`.rationale/` es YAML plano, revisado en el mismo pull request que el código." },
      { title: "Las trazas no salen", body: "La actividad guarda identificadores y una intención de una línea. Nunca código, prompts ni contenido de Records." },
      { title: "Centro de control de solo lectura", body: "127.0.0.1, solo GET, Host validado, assets embebidos." },
      { title: "Frontera con el proveedor", body: "Codebase Memory solo por sus herramientas públicas. No disponible significa desconocido, nunca completo." },
    ],

    releaseEyebrow: "Verdad de release",
    releaseTitle: "1.0 es estable. Esto es lo que significa.",
    releaseBody: "El ciclo completo está implementado, probado y en uso sobre el propio repositorio de Rationale.",
    releaseVerified: [
      "366 tests de Rust, Clippy, RustSec y validación de schemas",
      "Verificación desde checkout limpio y del binario empaquetado",
      "Migración del registro en Claude Code, Codex y Cursor",
      "Dogfood: un cambio real capturado y recuperado de extremo a extremo",
    ],
    releaseOpen: [
      "La polaridad léxica de los conflictos es una pista ruidosa",
      "Algunos ADRs están implementados pero siguen propuestos",
    ],
    releaseVerifiedLabel: "verificado",
    releaseOpenLabel: "abierto, dicho con claridad",
    releaseEvidence: "Leer la evidencia →",
    releaseLimits: "Límites conocidos →",

    installEyebrow: "Instalar / cerca de un minuto",
    installTitle: "Dale a tus agentes memoria para el porqué.",
    installBody: "El instalador verifica checksums y usa el canal estable. Actualizar o desinstalar nunca toca `.rationale/`.",
    installCompanion: "01 / Codebase Memory · recomendado",
    installStep1: "02 / Instalar Rationale · macOS + Linux",
    installStep2: "03 / Dentro de tu repositorio",
    installStep3: "04 / Abre el Control Room",
    installWindows: "¿Windows? El instalador de PowerShell está en el quickstart.",
    installRestart: "Reinicia tu agente. En Claude Code ejecuta `/rationale-health`; en Codex pide «Comprueba la salud de Rationale».",
    installCopy: "Copiar comando",
    copied: "Copiado",
    copyFailed: "Selecciona y copia",

    docsEyebrow: "Documentación",
    docsTitle: "Todo lo necesario para verificar lo que prometemos.",
    docsCards: [
      { slug: "quickstart", label: "Empezar", title: "Quickstart de cinco minutos", body: "Instala, conecta un agente, primer cambio gobernado." },
      { slug: "workflow", label: "Operar", title: "El ciclo", body: "Preparar, cambiar, capturar — y dónde decide una persona." },
      { slug: "control-room", label: "Observar", title: "Control Room", body: "El grafo, la memoria y la actividad en vivo." },
      { slug: "concepts", label: "Entender", title: "Conceptos clave", body: "Records, procedencia, autoridad, relaciones." },
      { slug: "mcp-reference", label: "Integrar", title: "Referencia MCP", body: "Cinco herramientas, seis prompts, una frontera." },
      { slug: "evidence", label: "Verificar", title: "Evidencia", body: "Contra qué se verificó 1.0 y qué sigue abierto." },
    ],

    footerLine: "Tu repo. Tu proceso. Tu contexto.",
    footerDocs: "Docs",
    footerGithub: "GitHub",
    footerLicense: "Licencia MIT",
    footerStatus: "v1.0.0 · sin telemetría remota",
  },
} as const;
